version: '3'

networks:
  private:
  public:
    external:
      name: web
services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    labels:
      - traefik.backend=yiicms
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:yiicms.lokal
      - traefik.port=80
    networks:
      - private
      - public
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated